// const items = [
//   {
//     id: "u9kgwNWGi3uUUwh0b8V49",
//     animal: "Dog",
//     text: "Сute dog looking for a home",
//     favorite: true,
//     category: "in good hands",
//     location: "Kropivnitsckiy-ппдщлмщщлщ",
//   },
//   {
//     id: "YxhM4QDxPeA3SmPHcEZPJ",
//     animal: "chinchilla",
//     text: "Сute dog looking for a home",
//     favorite: false,
//     category: "sell",
//     location: "Kropivnitsckiy",
//   },
//   {
//     id: "zCd_RioNMOBaQwAXnc8Px",
//     animal: "guinea pig",
//     text: "Сute dog looking for a home",
//     favorite: false,
//     category: "in good hands",
//     location: "Kropivnitsckiy",
//   },
//   {
//     id: "ck89qe3HriUDHe09TBoJ8",
//     animal: "Hamster",
//     text: "Сute dog looking for a home",
//     favorite: true,
//     category: "sell",
//     location: "Kropivnitsckiy",
//   },
//   {
//     id: "e1Tpn_I3wBkLREY6wG0lb",
//     animal: "Rabbit",
//     text: "Сute dog looking for a home",
//     favorite: false,
//     category: "in good hands",
//     location: "Kropivnitsckiy",
//   },
//   {
//     id: "Op8ApLTY0-Vn2cR0vDIwG",
//     animal: "Cat",
//     text: "Сute dog looking for a home",
//     favorite: true,
//     category: "sell",
//     location: "Kropivnitsckiy",
//   },
//   {
//     id: "dkJSszfrRVtLVR_MfRqcu",
//     animal: "chinchilla",
//     text: "Сute dog looking for a home",
//     favorite: false,
//     category: "in good hands",
//     location: "Kropivnitsckiy",
//   },
//   {
//     id: "CTHE0f1kkWwqS5sL2tI8_",
//     animal: "guinea pig",
//     text: "Сute dog looking for a home",
//     favorite: true,
//     category: "sell",
//     location: "Kropivnitsckiy",
//   },
//   {
//     id: "CTHE0f1kkWwqS5sL2tIcu",
//     animal: "Hamster",
//     text: "Сute dog looking for a home",
//     favorite: false,
//     category: "in good hands",
//     location: "Kropivnitsckiy",
//   },
//   {
//     id: "CTHE0f1kkWwqS5sL2tI10",
//     animal: "Rabbit",
//     text: "Сute dog looking for a home",
//     favorite: true,
//     category: "in good hands",
//     location: "Kropivnitsckiy",
//   },
//   {
//     id: "CTHE0f1kkWwqS5sL2tI11",
//     animal: "Cat",
//     text: "Сute dog looking for a home",
//     favorite: false,
//     category: "sell",
//     location: "Kropivnitsckiy",
//   },
//   {
//     id: "CTHE0f1kkWwqS5sL2tI12",
//     animal: "Dog",
//     text: "Сute dog looking for a home",
//     favorite: true,
//     category: "in good hands",
//     location: "Kropivnitsckiy",
//   },
// ];

// export default items;